# Generated by Django 4.0.4 on 2022-05-03 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='note',
            name='favorite',
            field=models.BooleanField(default=False),
        ),
    ]
